paths:
  /api/products:
    get:
      summary: Obtenemos la paginacion de los productos
      tags:
        - Products
      responses:
        "200":
          description: Se obtiene la informacion para paginar los productos
          content:
            aplication/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "500":
          description: Error interno del servidor
    post:
      summary: Este endpoint crea un producto
      tags:
      - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/createProduct"
      responses:
        "201":
          description: Producto creado correctamente
        "500":
          description: Error en el servidor

  /api/products/{pid}:
    get:
      summary: Obtiene un producto por su ID
      tags:
      - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: ID del producto que se quiere buscar
        schema:
          type: string
      responses:
        "200":
          description: Producto encontrado
          content:
            aplication/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "500":
          description: Error interno del servidor.
    put:
      summary: Actualiza un producto por su ID
      tags:
      - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: ID del producto que se quiere buscar
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/updateProduct"
      responses:
        "200":
          description: Producto actualizado correctamente
        "500":
          description: Error en el servidor
    delete:
      summary: Elimina un producto por su ID
      tags:
      - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: ID del producto que se quiere buscar
        schema:
          type: string
      responses:
        "200":
          description: Producto eliminado correctamente
        "500":
          description: Error en el servidor
  /api/products/{pid}/notify/{uid}:
    post:
      summary: Agrega un usuario al producto para ser notificado de stock
      tags:
      - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: ID del producto que se quiere buscar, el stock del mismo debe ser 0
        schema:
          type: string
      - name: uid
        in: path
        required: true
        description: ID del usuario que quiere ser notificado
        schema:
          type: string
      responses:
        "200":
          description: Usuario agregado a array de notificacion correctamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor
  /api/products/{pid}/favorite/{uid}:
    post:
      summary: Agrega un producto como favorito
      tags:
      - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: ID del producto que se quiere buscar
        schema:
          type: string
      - name: uid
        in: path
        required: true
        description: ID del usuario que quiere ser notificado
        schema:
          type: string
      responses:
        "200":
          description: Producto agregado como favorito
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID autogenerado por MongoDB
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripcion del producto
        price:
          type: number
          description: Precio del producto
        code:
          type: string
          description: Codigo de producto, el mimso debe ser unico
        stock:
          type: number
          description: Cantidad de productos disponibles en el stock
        category:
          type: string
          description: Categoria del producto
  requestBodies:
    createProduct:
      type: object
      properties:
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripcion del producto
        price:
          type: number
          description: Precio del producto
        code:
          type: string
          description: Codigo de producto, el mimso debe ser unico
        stock:
          type: number
          description: Cantidad de productos disponibles en el stock
        category:
          type: string
          description: Categoria del producto
      example:
        title: Producto de prueba swagger
        description: Este producto esta creado desde swagger
        price: 200
        code: prdswg
        stock: 5
        category: test
    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripcion del producto
        price:
          type: number
          description: Precio del producto
        stock:
          type: number
          description: Cantidad de productos disponibles en el stock
        category:
          type: string
          description: Categoria del producto
      example:
        title: Producto de prueba swagger actualizado
        description: Se actualiza el producto desde swagger
        price: 12.59
        stock: 2300
        category: test
